### ISSUE TITLE
Python version requirements are wrong

### ISSUE THREAD

**Issue by Alexgmin** [escodebar/django-rest-framework-rules#3]
Since 2.7 is supported, as indicated on PyPi and the test setup, the current version specifier, https://github.com/escodebar/django-rest-framework-rules/blob/321663e67ec1fe1600c92c9bad3748267bc4cdc4/setup.py#L38 indicates that 2.7 is not supported.

From the pip verbose log, with Python 2.7.12
`(from https://pypi.python.org/simple/django-rest-framework-rules/) (requires-python:>=2.7, >=3.5.*, <4) is incompatible with the pythonversion in use. Acceptable python versions are:>=2.7, >=3.5.*, <4`

**Comment by escodebar** [comment]
Hi Alex and thank you for the issue.

I'm going to drop support for python 2.7, since Django itself is dropping support for Python 2.
